version: 1.4.9.8a{build}
max_jobs: 15
image: Visual Studio 2017
configuration: Release
platform: x86
test: off

environment:
  matrix:
  - step_name: 1
  - step_name: 2
  - step_name: 3
  - step_name: 4
  - step_name: 5
  - step_name: 6
  - step_name: 7
  - step_name: 8
  - step_name: 9
  - step_name: 10
  - step_name: 11
  - step_name: 12 

before_build:
- cmd: call ci_build.bat

#cache:
#  - .\externals\cpython
#  - .\externals\aes

build:
  project: Els_kom_Solution.sln
  parallel: true
  verbosity: minimal
